In [1]:
import numpy as np
from quant_met import hamiltonians, utils, plotting

In [2]:
lattice_constant = np.sqrt(3)
egx_h = hamiltonians.EGXHamiltonian(t_gr=1, t_x=0.01, V=1, a=lattice_constant, mu=0, U_x=1, U_gr=1)

all_K_points = 4 * np.pi / (3 * lattice_constant) * np.array([
    (np.sin(i * np.pi / 6), np.cos(i * np.pi / 6)) for i in [1, 3, 5, 7, 9, 11]]
)
nkx = 2
nky = 2

BZ_grid = utils.generate_uniform_grid(nkx, nky, all_K_points[1], all_K_points[5], origin=np.array([0, 0]))

energies, bloch = egx_h.generate_bloch(BZ_grid)

print(hamiltonians.calculate_current_op(egx_h, 0, k_points=BZ_grid))

[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[-1.11022302e-08  3.98082895e-02  2.00000000e+08]
  [-1.47816733e+00  6.77505757e-10 -2.28374038e-02]
  [-2.00000000e+08  1.36735450e+00  0.00000000e+00]]

 [[-3.33066907e-08  5.97868554e-03 -3.16400189e-08]
  [ 2.21650308e-02  7.19139087e-10  7.61334299e-01]
  [-3.14044987e-08  2.05358551e-01  2.22044605e-08]]

 [[ 0.00000000e+00  3.85265215e-02  2.00000000e+08]
  [-7.39083524e-01  4.20766635e-10 -1.14186308e-02]
  [-2.00000000e+08  1.32333212e+00  0.00000000e+00]]]


/Users/tjark/Projects/Research/quant-met/src/quant_met/hamiltonians/_superfluid_weight.py:37: ComplexWarning: Casting complex values to real discards the imaginary part
  current_op[k_index, m, n] = (energy[m] - energy[n]) * np.dot(


[-4.6948071  -0.79866576 -0.79866576 -0.79866576]
-1.7727010943743071
