In [1]:
import numpy as np
from quant_met import hamiltonians, utils, plotting

In [11]:
lattice_constant = np.sqrt(3)
egx_h = hamiltonians.EGXHamiltonian(t_gr=1, t_x=0.01, V=1, a=lattice_constant, mu=0, U_x=1, U_gr=1)

all_K_points = 4 * np.pi / (3 * lattice_constant) * np.array([
    (np.sin(i * np.pi / 6), np.cos(i * np.pi / 6)) for i in [1, 3, 5, 7, 9, 11]]
)
nkx = 2
nky = 2

BZ_grid = utils.generate_uniform_grid(nkx, nky, all_K_points[1], all_K_points[5], origin=np.array([0, 0]))

energies, bloch = egx_h.generate_bloch(BZ_grid)

print(hamiltonians.calculate_current_op(egx_h, 0, k_points=BZ_grid))

[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 3.33066907e-08  3.99617677e-02  2.00000000e+08]
  [-1.47816733e+00  6.93889390e-10 -2.28373933e-02]
  [-2.00000000e+08  1.37262623e+00 -2.22044605e-08]]

 [[ 1.11022302e-08  6.52488520e-03  1.58200097e-08]
  [ 2.21650310e-02  7.73541963e-10  7.61334305e-01]
  [ 3.16400189e-08  2.24119665e-01  0.00000000e+00]]

 [[ 2.22044605e-08  3.73377642e-02  2.00000000e+08]
  [-7.39083493e-01  7.96525947e-11 -1.14186511e-02]
  [-2.00000000e+08  1.28250017e+00 -2.22044605e-08]]]
