In [1]:
from quant_met import hamiltonians
from quant_met.minimize_free_energy import free_energy
import numpy as np

In [5]:
lattice_constant = np.sqrt(3)
beta = 100

graphene_h = hamiltonians.GrapheneHamiltonian(t_nn=1, a=lattice_constant, mu=-1, coulomb_gr=2)

#print(graphene_h.hamiltonian_k_space(np.array([[1, 1], [0, 0]])))
print(free_energy(delta_vector=np.array([1, -1]), beta=beta, hamiltonian=graphene_h, k_points=np.array([[0, 0], [1, 1], [2, 2], [3, 3]])))
print(free_energy(delta_vector=np.array([1, 1]), beta=beta, hamiltonian=graphene_h, k_points=np.array([[0, 0], [1, 1], [2, 2], [3, 3]])))

[[-2.16227766 -2.16227766  4.16227766  4.16227766]
 [-1.07430438 -0.84977221  2.84977221  3.07430438]
 [-1.25785788  0.38363716  1.61636284  3.25785788]
 [-2.05763806 -0.39809122  2.39809122  4.05763806]]
[0.5 0.5]
1.0
[1. 1. 1. 1.]
0.19608556141015557
[[-3.         -1.          3.          5.        ]
 [-1.68644799  0.2876847   1.7123153   3.68644799]
 [-0.97944503 -0.24884856  2.24884856  2.97944503]
 [-1.80607633 -0.85195712  2.85195712  3.80607633]]
[0.5 0.5]
1.0
[1. 1. 1. 1.]
0.2335598310347222
