In [1]:
import sympy as sp
from IPython.display import display

In [2]:
sp.init_printing(use_latex='mathjax')
#f = sp.symbols('f', complex=True)
t_X, V = sp.symbols('t_X, V', real=True, positive=True)
hamiltonian = sp.Matrix([[0, 0, V], [0, 0, 0], [V, 0, 3 * t_X]])
display(hamiltonian)
print(hamiltonian.is_diagonalizable())

⎡0  0    V  ⎤
⎢           ⎥
⎢0  0    0  ⎥
⎢           ⎥
⎣V  0  3⋅t_X⎦

True


In [3]:
bloch_matrix, diagonal_matrix = hamiltonian.diagonalize(normalize=True, sort=True)
#display(hamiltonian.eigenvects(normalize=True, sort=True))
display(sp.simplify(bloch_matrix))
display(bloch_matrix.subs({t_X: 0.01, V: 0.1}))
display(sp.simplify(diagonal_matrix))

⎡                       _______________                              _________
⎢                      ╱    2        2                              ╱    2    
⎢           -3⋅t_X - ╲╱  4⋅V  + 9⋅t_X                    -3⋅t_X + ╲╱  4⋅V  + 9
⎢0  ───────────────────────────────────────────  ─────────────────────────────
⎢        ______________________________________       ________________________
⎢       ╱                                    2       ╱                        
⎢      ╱         ⎛           _______________⎞       ╱         ⎛           ____
⎢     ╱      2   ⎜          ╱    2        2 ⎟      ╱      2   ⎜          ╱    
⎢   ╲╱    4⋅V  + ⎝3⋅t_X + ╲╱  4⋅V  + 9⋅t_X  ⎠    ╲╱    4⋅V  + ⎝3⋅t_X - ╲╱  4⋅V
⎢                                                                             
⎢1                       0                                            0       
⎢                                                                             
⎢                       2⋅V                         

⎡0  -0.757740210405336  0.652556337441357⎤
⎢                                        ⎥
⎢1          0                   0        ⎥
⎢                                        ⎥
⎣0  0.652556337441357   0.757740210405336⎦

⎡0              0                           0             ⎤
⎢                                                         ⎥
⎢              _______________                            ⎥
⎢             ╱    2        2                             ⎥
⎢   3⋅t_X   ╲╱  4⋅V  + 9⋅t_X                              ⎥
⎢0  ───── - ──────────────────              0             ⎥
⎢     2             2                                     ⎥
⎢                                                         ⎥
⎢                                          _______________⎥
⎢                                         ╱    2        2 ⎥
⎢                               3⋅t_X   ╲╱  4⋅V  + 9⋅t_X  ⎥
⎢0              0               ───── + ──────────────────⎥
⎣                                 2             2         ⎦

In [14]:
delta_1, delta_2, delta_3 = sp.symbols('Delta_1, Delta_2, Delta_3')
delta_orbital = sp.Matrix([[delta_1, 0, 0], [0, delta_2, 0], [0, 0, delta_3]])
display(sp.simplify(bloch_matrix * delta_orbital * sp.conjugate(bloch_matrix.T)))

⎡      3⋅Δ₂⋅t_X         Δ₂         3⋅Δ₃⋅t_X         Δ₃                        
⎢──────────────────── + ── - ──────────────────── + ──  0                     
⎢     _______________   2         _______________   2                         
⎢    ╱    2        2             ╱    2        2                              
⎢2⋅╲╱  4⋅V  + 9⋅t_X          2⋅╲╱  4⋅V  + 9⋅t_X                               
⎢                                                                             
⎢                          0                            Δ₁                    
⎢                                                                             
⎢                    V⋅(-Δ₂ + Δ₃)                                   3⋅Δ₂⋅t_X  
⎢                 ──────────────────                    0   - ────────────────
⎢                    _______________                               ___________
⎢                   ╱    2        2                               ╱    2      
⎣                 ╲╱  4⋅V  + 9⋅t_X                  

In [11]:
import numpy as np
from quant_met import hamiltonians

lattice_constant = np.sqrt(3)

K = 4 * np.pi / (3 * lattice_constant) * np.array([1, 0])

egx_h = hamiltonians.EGXHamiltonian(t_gr=1, t_x=0.01, V=1, a=lattice_constant, mu=0, U_gr=1, U_x=1)

energies, bloch = egx_h.generate_bloch(K)

np.set_printoptions(suppress=True, precision=4)

print(np.real(egx_h.k_space_matrix(K)))

#print(f"Energies: {np.round(energies, decimals=4)}")
#print(f"Bloch matrix:\n {np.real(np.round(bloch, decimals=4))}")
print(f"Energies: {energies}")
print(f"Bloch matrix:\n {np.real(bloch)}")

[[[0.   0.   1.  ]
  [0.   0.   0.  ]
  [1.   0.   0.03]]]
Energies: [-0.9851  0.      1.0151]
Bloch matrix:
 [[ 0.7124  0.      0.7018]
 [-0.      1.      0.    ]
 [-0.7018 -0.      0.7124]]
